### ISSUE TITLE
Determine Point of Contacts

### ISSUE THREAD

**Issue by HiGregory** [HiGregory/datagov#3]
We are excited to launch this initiative with our first low-hanging fruit. The next step is to determine the Point of Contacts on behalf of each organization.

- [x] City of Coral Gables 1. Chris Cowen, Data Analyst 2. Leighton Shervington, GIS/CIC Analyst (Assigned by Raimundo)
- [x] Microsoft 1. Gregory Johnson, Miami Civic Innovation
- [x] City of Miami (Cheriene F. and Jen H.)
- [x] Miami Dade County, Enterprise Division

**Comment by gisbear** [comment]
Additional Coral Gables team members: Mark Hebert, GIS Mgr; Peterson Pierre Louis, GIS Analyst; Mike Lopez, GIS Technician; Alina Mehdi, IT Technician.

Thanks.
